# Generated by Django 4.2.6 on 2023-10-30 03:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("todo", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="todo",
            options={"verbose_name": "Task", "verbose_name_plural": "Tasks"},
        ),
        migrations.RenameField(
            model_name="todo",
            old_name="is_closed",
            new_name="is_complete",
        ),
    ]
