# Generated by Django 4.2.6 on 2023-10-30 12:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("todo", "0002_alter_todo_options_rename_is_closed_todo_is_complete"),
    ]

    operations = [
        migrations.AlterField(
            model_name="todo",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
